export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  aiProvider: process.env.AI_PROVIDER ?? "",
  anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
  anthropicApiUrl:
    process.env.ANTHROPIC_API_URL ?? "https://api.anthropic.com/v1",
  anthropicModel: process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-6",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  geminiApiUrl:
    process.env.GEMINI_API_URL ??
    "https://generativelanguage.googleapis.com/v1beta/openai",
  geminiModel: process.env.GEMINI_MODEL ?? "gemini-2.5-flash",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  gumroadWebhookSecret: process.env.GUMROAD_WEBHOOK_SECRET ?? "",
  publicSiteUrl: process.env.PUBLIC_SITE_URL ?? process.env.VITE_PUBLIC_SITE_URL ?? "",
  payuniMerId: process.env.PAYUNI_MER_ID ?? "",
  payuniHashKey: process.env.PAYUNI_HASH_KEY ?? "",
  payuniHashIv: process.env.PAYUNI_HASH_IV ?? "",
  payuniMode: process.env.PAYUNI_MODE ?? "production",
  lineChannelId: process.env.LINE_CHANNEL_ID ?? "",
  lineChannelSecret: process.env.LINE_CHANNEL_SECRET ?? "",
  lineMessagingAccessToken: process.env.LINE_MESSAGING_ACCESS_TOKEN ?? "",
  ownerLineUserId: process.env.OWNER_LINE_USER_ID ?? "",
  lineLoginRedirectUri: process.env.LINE_LOGIN_REDIRECT_URI ?? "",
  lineLoginRequestEmail: process.env.LINE_LOGIN_REQUEST_EMAIL === "true",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
};
